### ISSUE TITLE
Warning on Linux

### ISSUE THREAD

**Issue by Joe-K0OG** [bazineta/js8call#5]
Allan,

The latest commit cfa3b9a (Improve RDP...) yields the following warning on Linux.  It builds & runs, but thought you might want to address this:

[ 96%] Building CXX object CMakeFiles/js8call.dir/qrc_wsjtx.cpp.o
[ 97%] Building CXX object CMakeFiles/js8call.dir/js8call_autogen/EWIEGA46WW/qrc_images.cpp.o
In file included from /usr/include/x86_64-linux-gnu/qt6/QtCore/QBitArray:1,
                 from /js8call/js8call-prefix/src/RDP.hpp:4,
                 from /js8call/js8call-prefix/src/RDP.cpp:1:
In member function ‘void QBitArray::setBit(qsizetype)’,
    inlined from ‘QList<QPointF>::iterator RDP::operator()(QPolygonF&, qreal)’ at /js8call/js8call-prefix/src/RDP.cpp:88:19:
/usr/include/x86_64-linux-gnu/qt6/QtCore/qbitarray.h:90:66: warning: ‘index’ may be used uninitialized [-Wmaybe-uninitialized]
   90 | (reinterpret_cast<uchar*>(d.data())+1+(i>>3)) |= uchar(1 << (i & 7)); }
      |                                                             ~~~^~~~

/js8call/js8call-prefix/src/RDP.cpp: In member function ‘QList<QPointF>::iterator RDP::operator()(QPolygonF&, qreal)’:
/js8call/js8call-prefix/src/RDP.cpp:66:15: note: ‘index’ was declared here
   66 |     qsizetype index;[ 96%] Building CXX object CMakeFiles/js8call.dir/qrc_wsjtx.cpp.o
[ 97%] Building CXX object CMakeFiles/js8call.dir/js8call_autogen/EWIEGA46WW/qrc_images.cpp.o
In file included from /usr/include/x86_64-linux-gnu/qt6/QtCore/QBitArray:1,
                 from /js8call/js8call-prefix/src/RDP.hpp:4,
                 from /js8call/js8call-prefix/src/RDP.cpp:1:
In member function ‘void QBitArray::setBit(qsizetype)’,
    inlined from ‘QList<QPointF>::iterator RDP::operator()(QPolygonF&, qreal)’ at /js8call/js8call-prefix/src/RDP.cpp:88:19:
/usr/include/x86_64-linux-gnu/qt6/QtCore/qbitarray.h:90:66: warning: ‘index’ may be used uninitialized [-Wmaybe-uninitialized]
   90 | (reinterpret_cast<uchar*>(d.data())+1+(i>>3)) |= uchar(1 << (i & 7)); }
      |                                                             ~~~^~~~

/js8call/js8call-prefix/src/RDP.cpp: In member function ‘QList<QPointF>::iterator RDP::operator()(QPolygonF&, qreal)’:
/js8call/js8call-prefix/src/RDP.cpp:66:15: note: ‘index’ was declared here
   66 |     qsizetype index;
      |               ^~~~~
[ 97%] Linking CXX executable js8call
[100%] Built target js8call

      |               ^~~~~[ 96%] Building CXX object CMakeFiles/js8call.dir/qrc_wsjtx.cpp.o
[ 97%] Building CXX object CMakeFiles/js8call.dir/js8call_autogen/EWIEGA46WW/qrc_images.cpp.o
In file included from /usr/include/x86_64-linux-gnu/qt6/QtCore/QBitArray:1,
                 from /js8call/js8call-prefix/src/RDP.hpp:4,
                 from /js8call/js8call-prefix/src/RDP.cpp:1:
In member function ‘void QBitArray::setBit(qsizetype)’,
    inlined from ‘QList<QPointF>::iterator RDP::operator()(QPolygonF&, qreal)’ at /js8call/js8call-prefix/src/RDP.cpp:88:19:
/usr/include/x86_64-linux-gnu/qt6/QtCore/qbitarray.h:90:66: warning: ‘index’ may be used uninitialized [-Wmaybe-uninitialized]
   90 | (reinterpret_cast<uchar*>(d.data())+1+(i>>3)) |= uchar(1 << (i & 7)); }
      |                                                             ~~~^~~~

/js8call/js8call-prefix/src/RDP.cpp: In member function ‘QList<QPointF>::iterator RDP::operator()(QPolygonF&, qreal)’:
/js8call/js8call-prefix/src/RDP.cpp:66:15: note: ‘index’ was declared here
   66 |     qsizetype index;
      |               ^~~~~
[ 97%] Linking CXX executable js8call
[100%] Built target js8call

[ 97%] Linking CXX executable js8call
[100%] Built target js8call

73,
-Joe-
K0OG

**Comment by Joe-K0OG** [comment]
Allan,

I just did a test build on Win10 and get the same warning there as well.

73,
-Joe-
K0OG

**Comment by Joe-K0OG** [comment]
Allan,

Fix for the above warning:  Modify line 66 of RDP.cpp to read as follows to initialize the index...

    qsizetype index = 0;

73,
-Joe-

**Comment by bazineta** [comment]
For reasons that are unclear to me, I'm not getting notifications here. That should be resolved, now, Joe.

**Comment by Joe-K0OG** [comment]
Yeah, the latest builds with no warnings on Windows and Linux.  All is good now :)

73,
-Joe-
K0OG

**Comment by radio-miskovice** [comment]
Joe, could I ask you also for replacing Input | Output device critical error message box by device reinitialization next time you will be doing build? I am still unable to build for windows, this time I tried with a "clean" setup using just MSys2 but this time it fails even during the configure phase. A have another instance built successfully from source running on Pi4 but that one is now in radio club and I probably won't have time to go there and experiment with another build, yet.
The reason is that some transceivers seem to have unreliable USB stream, unfortunately the models we intend to use as ultra-portable equipment in case of emergencies (in my case QMX, QDX) but it also happened with Kenwood TS-590 in the radio club. Therefore the critical audio error is not a matter whether it happens or not, it is a matter of time when it does happen, hence a reliable recovery procedure is needed for stations that will not be attended 24/7. Also, what would help, if the audio critical error could create a file, so that external program, e.g. a cron job, could hard-kill and hard-restart JS8Call in such situations.
Thank you and sorry for annoying you. Unfortunately the whole JS8Call source seems to be extremely complicated and difficult to set up for a successful build.

**Comment by Joe-K0OG** [comment]
Jindra,

I'm sorry, but I'm not capable of modifying the error handling for the I/O.  Perhaps Allan will have some insight into that. 

Regardless of improving error handling, your *real* solution is to stabilize the device handling.  Make sure SLEEP (power down) is DISABLED for ALL USB ports (and ALL devices) on your PCs, as well as disabling sleep on the PC itself.  If anything goes to sleep, it will break connection with the software, and hang.  The default USB power settings in the Windows Power Management console are sugh that if the system does not detect activity for a while, it will power off the seemingly "unused" devices, and break your connection.

73,
-Joe-
K0OG
